# Generated by Django 5.0.6 on 2024-09-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KohiLocale', '0005_remove_userprofile_favorite_coffee_shops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeshop',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='coffeeshopapplication',
            name='image_url',
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coffee_shops/'),
        ),
        migrations.AddField(
            model_name='coffeeshopapplication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
        migrations.AddField(
            model_name='promo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promos/'),
        ),
    ]
